# jobs
job_max_running = 3 # Maximum running job that will be processed before taking new job from quque 
job_processed_interval_ms = 200 # Interval between processing job in millisecond

# file handler
chunk_size_per_transmission = 5 # chunk size of image binary that will be sent per transmission

# http
http_host = "127.0.0.1" # Change this to 0.0.0.0 when running from docker to allow all connection
http_port = 7777

# mqtt
mqtt_client_id = "rocky"
mqtt_host = "broker.emqx.io"
mqtt_port = 1883

